# Generated by Django 4.0.5 on 2022-12-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
    ]
